### ISSUE TITLE
galaxyRoot checker

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy-language-server#157]
Hi,
Thank you so much for this. When I watched your talk I immediately installed it.
I needed to fight a while because my `galaxyRoot` was said invalid.
Reading the code I found:
https://github.com/galaxyproject/galaxy-language-server/blob/a22b1e79f747fd476587680ba0c74ee92b7d667a/client/src/configuration/galaxyToolWorkspaceConfiguration.ts#L69
Mine was ending by `galaxy-dev`.
I think it would be great to also consider it as valid.

Thanks

**Comment by davelopez** [comment]
Hey @lldelisle! Thank you so much for trying it and for reporting issues! they are much appreciated.

I will fix it so it is less restrictive and a bit "smarter" :)

**Comment by lldelisle** [comment]
Thank you very much you are so reactive...
