### ISSUE TITLE
vscode add more planemo options

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy-language-server#161]
Hi,
Sorry me again...
It would be great if we could use for example `--no_cleanup` or `--job_output_files` for planemo tests...
Thanks

**Comment by davelopez** [comment]
Nothing to be sorry about! just the opposite! this is the kind of feedback that we need, please keep it coming :)

I must confess I am not a proper tool developer myself (I just wrapped a really simple one :laughing:) so the feedback coming from more experienced tool developers is of huge importance here!

Please make a list of all the options that will be useful for you and we will try to add all of them to the settings. And thanks again for your feedback, it is really appreciated!

**Comment by bernt-matthias** [comment]
`--update_test_data` might be useful as well.
