### ISSUE TITLE
Failed installation due to missing prerequisites results in continous failure

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy-language-server#195]
Steps to reproduce:

1. Install extension on VSCode on Ubuntu 22.04 machine without python3-venv package but where you are running in a conda environment. Click the button to do post-installation task.
2. See the post-installation task fail. Read the docs, install python3-venv and try and uninstall and re-install the extension. Click the post-installation button again and watch it fail.

What's going on here is that a venv was created by step (1) probably because virtualenv was available in conda and that venv didn't have pip in it so installation failed. Uninstalling the extension didn't remove the broken venv. The solution for me was to manually remove it with `rm -rf ~/.vscode/extensions/davelopez.galaxy-tools-0.7.1/` and re-do the installation of the extension (this is after ensuring that python3-venv was on the system).

**Comment by davelopez** [comment]
Thank you @pvanheus for the report and the detailed explanation! I'll try to improve the installation experience in that case.
