### ISSUE TITLE
Support and test wider range of python versions

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy-language-server#199]
GLS seems to have a strict python 3.8 requirement. Wondering if this can be made more flexible, e.g. supporting a minimal and maximal python version. 

The latest Ubuntu LTS for instance has a default of python 3.10 which requires me to setup a 3.8 conda env

**Comment by davelopez** [comment]
Python 3.8 is supposed to be the minimum required version (just for creating the local environment), but you are right, there is now something in the way that it is detecting newer Python versions that is not entirely right. I will check and see if I can improve it.

Thanks for reporting!

**Comment by davelopez** [comment]
I just checked this and it is a silly mistake on my side in the regex for parsing the Python version, it was interpreting `3.10` as `3.1` so it was not matching the `3.8+` requirement :man_facepalming: :sweat_smile: 

Thanks again for letting me know @bernt-matthias!

**Comment by davelopez** [comment]
Fixed in #200
