### ISSUE TITLE
Add basic snippets to Extension

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy-language-server#20]
It would be interesting to have some code snippets to quickly add common sections to a tool or create basic tool boilerplate structure.
For example, if we write ``gtool`` in an empty document, a basic tool structure may autocomplete similar to the output of the command:
````
$ planemo tool_init --id 'sample' --name 'Sample Tool'
```` 
like:
```xml
<tool id="sample" name="Sample Tool" version="0.1.0">
    <requirements>
    </requirements>
    <command detect_errors="exit_code"><![CDATA[
        TODO: Fill in command template.
    ]]></command>
    <inputs>
    </inputs>
    <outputs>
    </outputs>
    <help><![CDATA[
        TODO: Fill in help.
    ]]></help>
</tool>
```

**Comment by bgruening** [comment]
Can we have two words? Then you could do something like `gsnippet tool` or `gsnippet conditional`, `gsnippet bool`

**Comment by davelopez** [comment]
I don't think you can have two separate words as snippet prefix, but I think is not really necessary. You can start typing, for example, just ``gtc`` for a snippet with prefix ``gtconditional`` and you will see autocompletion for the whole ``gtconditional``, then you can press enter or tab and the snippet will be inserted.
It seems to be really easy to create such snippets, it is really just add some data to a ``.json`` file.
I will add this first ``gtool`` snippet as a sample because it is easier to show than to explain 😄

**Comment by davelopez** [comment]
@bgruening you can see the working sample at #21 😉

**Comment by davelopez** [comment]
Basic documentation added [here](../blob/master/docs/CONTRIBUTING.md#adding-snippets) in case someone wants to contribute new snippets as first contribution :)

**Comment by bgruening** [comment]
Some snippets that we could add during a paper-cuts event:

* [ ] integer param
* [ ] boolean param with truevalue and falsevalue
* [ ] conditional param with select field
* [ ] text param with validator
* [ ] some common validators (URL, alphanumeric, comma-seperated-list)
* [ ] data param
* [ ] basic test section with expectd_num_output
* [ ] output-section (basic, collection, with filter, with advance filter)

**Comment by bgruening** [comment]
I think we have a good start already. More can be added if we see it.
