### ISSUE TITLE
Do not check comments

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy-language-server#212]
Hi,
This is a 'bug' report:
![image](https://user-images.githubusercontent.com/30404086/196614256-48eba513-9034-43d0-98f1-67eb3289c5e4.png)
If you need more info, please tell me.

**Comment by davelopez** [comment]
Thank you for the report @lldelisle!
I think we need to fix this directly in Galaxy where the tool linter code lives :+1:

**Comment by davelopez** [comment]
This should be fixed by https://github.com/galaxyproject/galaxy/pull/14845
