### ISSUE TITLE
Suddenly tracebacks 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy-language-server#219]
```
{'traceback': ['  File "/home/berntm/.vscode-oss/extensions/davelopez.galaxy-tools-0.10.0-universal/glsenv/lib/python3.10/site-packages/pygls/protocol.py", line 340, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/home/berntm/.vscode-oss/extensions/davelopez.galaxy-tools-0.10.0-universal/glsenv/lib/python3.10/site-packages/pygls/protocol.py", line 264, in _execute_request\n    self._send_response(msg_id, handler(params))\n', '  File "/home/berntm/.vscode-oss/extensions/davelopez.galaxy-tools-0.10.0-universal/glsenv/lib/python3.10/site-packages/galaxyls/server.py", line 114, in completions\n    if server.configuration.completion.mode == CompletionMode.DISABLED:\n']}
[Error - 12:24:31 PM] Request textDocument/completion failed.
  Message: AttributeError: 'dict' object has no attribute 'mode'
  Code: -32602 
```

**Comment by davelopez** [comment]
Thanks for reporting @bernt-matthias!

The latest version contains a major update of the underlying `pygls` library but I was hoping the tests would catch any breaking changes... 

I will investigate and try to fix it. In the meantime, if the extension is causing too much trouble, you can go back to the previous `0.9.0` version, there is no new functionality in 0.10.0 apart from all the updated dependencies and python 3.11 support.

On the other hand, if you keep using the latest version and detect any other traceback I will be very happy if you report them here :)

**Comment by davelopez** [comment]
@bernt-matthias, the new release 0.10.1 should fix this problem.

Sorry about that and please let me know if you find some other issues! :)

**Comment by bernt-matthias** [comment]
> the new release 0.10.1 should fix this problem.

seems to work. excellent.
