### ISSUE TITLE
linting complains about our tool version recommendations

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-language-server#234]
> Tool version [@TOOL_VERSION@+galaxy@VERSION_SUFFIX@] is not compliant with PEP 440.

**Comment by davelopez** [comment]
Hmmm, this is likely a Galaxy bug, the extension is just running the Galaxy linter and collecting the results. I'll investigate though... :+1:

**Comment by bgruening** [comment]
It looks like it does not take the macros into account.
