### ISSUE TITLE
Can we offer a select for param values?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-language-server#236]
Use case:

I have a select param. And I add now `display`. I get a nice suggestion from the editor, but it only puts in `display=""`. It would be nice to get in a next steps options which I can choose. In this case `checkboxes` and `radio`.

Related but not identical is if I type `optional`, I always get `optional=""`. But optional is a boolean and by default=false. So whenever I type it I want `optional="true"`

**Comment by davelopez** [comment]
I just checked and you can press `ctrl+space` (to manually invoke auto-completion) when you are inside the attribute value and it will show the valid values:

![attr-auto-complete](https://github.com/galaxyproject/galaxy-language-server/assets/46503462/8daebd34-b7d9-46d1-8203-1583286c66d8)

I will see if I can make appear the selection directly with a default value when you "tab-accept" the attribute containing enum values...

**Comment by bgruening** [comment]
If that does not work, maybe just document it is also enough. Cool!
