### ISSUE TITLE
reconsider automatic saving before code generation

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-language-server#237]
Users try to generate the cheetah or the tests, but if any small changes are in there it will not do anything. It gives you a message but I have seen users not recognise it.

What was the reason for not automatically saving?

**Comment by davelopez** [comment]
Not sure why, I guess the reason was likely not doing something that the user didn't expect (saving the file) but it could be acceptable to save it automatically before generating it as is not really a destructive action or something that cannot be reverted.

**Comment by bgruening** [comment]
I also think its not harmful so save.
