### ISSUE TITLE
Improve tag completion

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy-language-server#29]
Similar to #26, but this time for tags, it would be great to show the tags in the recommended order by the Galaxy tools [code style guidelines](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html?#coding-style).

We can also make use of the ``maxOccurs`` definition for each tag in the XSD and keep track in the context of the elements already included in the file to avoid displaying those tags that have reached the limit.

**Comment by davelopez** [comment]
Actually, to keep track in the context of the elements already included in the file, will require to change how the context parser works. Now, the context parser stops parsing a soon as it reaches the element under the cursor position. Although, until now, it was convenient, this behaviour does not allow to parse any possible elements defined after the cursor that should be taken into account.

One possible solution is to try to fully parse the whole file into a DOM (easy if the XML is well formed but somewhat difficult otherwise) and then find the element under the cursor and provide context information about it.

**Comment by bgruening** [comment]
Very true. I'm wondering how other XML based language servers solve this problem. Maybe we are using the wrong tool? Maybe something like https://www.crummy.com/software/BeautifulSoup/bs4/doc/ is better than a plain XML parser?

**Comment by davelopez** [comment]
Yeah, I tried to explore bs4, lxml and other libraries before, but unfortunately, they did not provide precise information about, for example, the exact position (line and offset) of a tag or attribute inside the document (or at least I couldn't find it), maybe just the line in some cases, so I have to find it manually anyway. Also, bs4 is a bit more tolerant to broken XML but still, if there are too many syntax errors, it is difficult to recover.
Anyway, I am going to try again to explore them now that I have more knowledge about what we really need, so thanks for pointing it out! :)
