### ISSUE TITLE
Add option to disable auto-complete but keep parsing?

### ISSUE THREAD

**Issue by NatPRoach** [galaxyproject/galaxy-language-server#54]
Hello, I was wondering if it would be possible to add an option in the VSCode version of this to disable the auto-complete functionality but keep the XML parsing functionality. I'm finding the extension very useful for catching bugs in writing Galaxy XMLs, but I'm generally not a fan of auto-complete so I'd appreciate a means of turning that part off.

**Comment by davelopez** [comment]
Hello @NatPRoach, thank you for your proposal!
I had planned to add some configuration parameters for the extension, but I was postponing it until I figured out which ones would be helpful, so I will put this in the backlog for the next version!
