### ISSUE TITLE
Generate test case based on inputs and outputs

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy-language-server#68]
We can try to define a custom command in the language server that generates a test case snippet based on the currently defined inputs and outputs.

The process can be:
1. The user writes the `inputs` and `outputs` sections of the tool.
2. The user invokes the `generate test command`, either by selecting it from the command palette or probably by using a keyboard shortcut.
3. The language server adds a new `test` element to the `tests` section and fills in the basic information.
4. The user edits the values and, in general, adapts the test case as necessary.

This could save some boilerplate typing when there are many parameters and allow to quickly build test cases.

Thanks @bgruening for the suggestion!

**Comment by bgruening** [comment]
Oh gosh, this would be a killer feature! And we could do the same for the command section.

**Comment by bgruening** [comment]
@davelopez this tool is a perfect test case for the feature described here: https://github.com/galaxyproject/tools-iuc/blob/master/tools/ena_upload/ena_upload.xml#L383

It has nested conditionals, with repeats, etc ... if such a section could be generated this would be amazing!
