### ISSUE TITLE
How to interact with the server from the command line?

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy-language-server#72]
Hi, thanks again for this great tool!

I'm trying to get the server to work with my editor, but am having problems verifying the server is working.

To start the server, I open up one shell and run:

* `python -m galaxyls --tcp --host=127.0.0.1 --port=2087`

And to interact with it, I open up another shell and run:

*  `socat - tcp:127.0.0.1:2087`, where I can then start sending strings to the server on every new line
    e.g. 

       TEST
       <param type="
       hello

And I can verify that the messages are being sent by checking the `galaxy-language-server.log` file to see:

```
DEBUG:pygls.protocol:Received b'TEST\n'
DEBUG:pygls.protocol:Received b'<param type="\n'
DEBUG:pygls.protocol:Received b'hello\n'
```

However, I cannot get any information back from the server. Is a response expect through this port? Or are there replies somewhere else I should be looking for?

Thanks

**Comment by davelopez** [comment]
Hi @mtekman!

The language server is an implementation of the [Language Server Protocol Specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/). This protocol uses messages with a simple HTTP like [header](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#headerPart) and content in [JSON-RPC 2.0](https://www.jsonrpc.org/specification).

These messages should be handled directly by your editor (if it supports the LS protocol) so you don't have to manually launch or send messages to the server.

In which editor are you trying to integrate the server?

**Comment by mtekman** [comment]
Ah okay. I knew the strings I was sending were not correctly formatted, I guess I was just surprised by the lack of any response at all -- but if that's expected, then I will need to keep debugging things on my side.

I'm trying to get it working with Emacs https://github.com/emacs-lsp/lsp-mode/pull/2333 in conjunction with the LSP package, but have run into the issues and suspected it might be the server not responding properly. Though I see now it's likely working fine it just needs proper headers from the editor.

Thanks -- I will close the issue then

**Comment by davelopez** [comment]
Cool!
I haven't used EMACS (and I am fairly new to the LSP world), but let me know if I can help you with anything :)

**Comment by bgruening** [comment]
@mtekman you can test the server with VSC and see if the server works. You could even try to capture the communication if that is needed.
