### ISSUE TITLE
Dependency problems

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy-language-server#78]
`pip install -r requirements-dev.txt` generates this output. I guess that it is necessary to include additional packages in the file.

![Screenshot from 2020-12-29 23-37-06](https://user-images.githubusercontent.com/26678117/103318763-bd9c7d80-4a2f-11eb-9d87-342436f27007.png)

**Comment by bgruening** [comment]
@gallardoalba your current python setup has just conflicting packages. You should create a new venv for the language server.

**Comment by davelopez** [comment]
Hey @gallardoalba! You can check the [getting started guide](https://github.com/galaxyproject/galaxy-language-server#getting-started) to create the virtual environment and install the development dependencies.
Let us know if you have any doubt! :)

**Comment by gallardoalba** [comment]
Yes, I activated the conda environment, and thought that it could avoid such conflics. Thanks!

**Comment by bgruening** [comment]
@gallardoalba can you outline exact your steps?

**Comment by bgruening** [comment]
btw. thanks for trying the GLS

**Comment by gallardoalba** [comment]
![Screenshot from 2020-12-30 00-06-30](https://user-images.githubusercontent.com/26678117/103319681-f38f3100-4a32-11eb-871f-bcb52a1ca6b8.png)

**Comment by davelopez** [comment]
So these steps still give you the dependency errors? Or is it working now?

**Comment by gallardoalba** [comment]
It worked after creating an environment with __virtualenv__.

**Comment by davelopez** [comment]
Glad you got it working!
Any changes that should be made to the [getting started documentation](https://github.com/galaxyproject/galaxy-language-server#getting-started)? or can we close this?

**Comment by gallardoalba** [comment]
It can be closed I guess.
