### ISSUE TITLE
How to change shortcuts

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy-language-server#92]
Using this in codium and did not found a way to change the `Ctrl+Alt+T` shortcut .. which opens a terminal on my gnome3 desktop (not sure if this is the gnome default).

**Comment by davelopez** [comment]
Hi @bernt-matthias!
I assume in VSCodium should be the same as in VSCode:

![image](https://user-images.githubusercontent.com/46503462/104725641-a7323980-5732-11eb-8ced-036875289dc8.png)

You can type the shortcut that you are looking for in the search bar and then change it to your preference.

![image](https://user-images.githubusercontent.com/46503462/104725813-e19bd680-5732-11eb-8280-5a144e33a84d.png)

Hope it helps! :)

**Comment by bernt-matthias** [comment]
Works. Thanks.
