### ISSUE TITLE
Integration with planemo

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy-language-server#95]
As a first approach to integrate some of the cool features of [`planemo`](https://github.com/galaxyproject/planemo) in the [`Galaxy Tools VSCode extension`](https://github.com/galaxyproject/galaxy-language-server/tree/master/client), we can start by including some configuration parameters like:
- `galaxyTools.planemo.pythonEnv`: this should be a path to the local Python binary in the virtual environment where planemo is installed.
- `galaxyTools.planemo.galaxy`: this should be a path to the local galaxy directory used as a value for the `--galaxy_root` parameter.

These two parameters should be enough to open the door to run `planemo` `lint`, `test`, and `serve` with the current tool and then report the results to the extension for display inside the IDE. These commands can also be bound to a keyboard shortcut for quick access.

**Comment by bgruening** [comment]
Can I propose `galaxyTools.planemo.docker` as well this will map to `planemo test --docker` and will enable running all test in Docker, like we do in IUC.

**Comment by davelopez** [comment]
Of course, it would be great to have a bit of brainstorming to come out with more options/ideas. And then study how can we implement them.
