### ISSUE TITLE
reorder attributes

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy-language-server#96]
Is there a possibility to reorder attributes?

**Comment by bgruening** [comment]
You mean according to the IUC standards https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html?highlight=ordering#coding-style ?

```
Order of parameter attributes:

    name
    argument
    type
    format
    min | truevalue
    max | falsevalue
    value | checked
    optional
    label
    help

```

Is this needed for a review? I guess our snippets should have the correct order, so using them would make this not needed.

**Comment by bernt-matthias** [comment]
Sure, but could be nice for existing tools.

**Comment by davelopez** [comment]
Yes, I think this should be possible by implementing a new custom command in the extension.

@bernt-matthias what will be your preferred use case?
- Target the `param` under the cursor and execute the command with some custom key shortcut.
- Execute the command and reorder all the attributes in all the `param` elements of the document.

Some possible preconditions before applying the reordering command that pop to mind are:
- The document must not have unsaved changes.
- The document must be valid and without syntax errors.
- The order of the attributes will be the one recommended by the IUC.

**Comment by bernt-matthias** [comment]
> Yes, I think this should be possible by implementing a new custom command in the extension.
> 
> @bernt-matthias what will be your preferred use case?
> 
>     * Target the `param` under the cursor and execute the command with some custom key shortcut.
> 
>     * Execute the command and reorder all the attributes in all the `param` elements of the document.

Hmm. Both sound useful to me. If you prefer to implement only one then I would go for the param under the cursor.

> Some possible preconditions before applying the reordering command that pop to mind are:
> 
>     * The document must not have unsaved changes.
> 
>     * The document must be valid and without syntax errors.
> 
>     * The order of the attributes will be the one recommended by the IUC.

3x yes.

**Comment by davelopez** [comment]
> Hmm. Both sound useful to me. If you prefer to implement only one then I would go for the param under the cursor.

Sure, there can be two different commands or key shortcuts for both options :)
